---
name: Continuous Unit test case execution
on: workflow_dispatch
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v7
      - name: Install dependencies
        run: npm ci
      - name: Run Unit test cases
        run: npm test 
